version: "2.1"

services:
  api:
    build: ./api
    working_dir: /var/www/html/api
    volumes:
      - ./api:/var/www/html/api

  web:
    image: nginx:1.16
    ports:
      - "${PORT-8080}:80"
    volumes:
      - ./dist:/var/www/html
      - ./api:/var/www/html/api
      - ./web/conf:/etc/nginx/conf.d

  client:
    image: node:12.13
    working_dir: /usr/src/app
    command: npm run dev
    volumes:
      - ./:/usr/src/app

  database:
    image: mysql:8.0
    command: [--character-set-server=utf8mb4, --default-authentication-plugin=mysql_native_password]
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cnif
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:5.0

volumes:
  database:
    driver: local
